### PR TITLE
Bugfix694 personal information

### LINKED ISSUE #694: [Bug Report] Personal information does not appear on the personal page
**Describe the bug**
Personal information does not appear on the personal page when the User opens "Oсобистий кабінет" but we can see partly this information on the "Автори" page and picture in the icon on the right top corners.

**Reproducible:** always
**Build found:** Release
**Resolution:** Unresolved;

**Preconditions**
1. The user is logged in as an Author Олег Петренко.
2. "Oсобистий кабінет" page is open.

**Steps to reproduce**
1. Pay attention to the information on the personal page.

**Actual result**
Personal information does not appear on the personal page when the User opens "Oсобистий кабінет" but we can see partly this information on the "Автори" page and picture in the icon on the right top corners.
Also we can see this information - when log as Admin and go to the "Адміністрування"-> "Список авторів"

**Expected result**
Personal information appears on the personal page when the User opens "Oсобистий кабінет" and it's the same information that we see on the "Автори" page.

**Desktop**
OS: Windows 11 Pro, version 22H2
Browser: Opera One version (101.0.4843.43)

**Additional Information** 
This defect is also reproduced on the "Admin" page.

**Attachments**
Screenshot 2023-09-27 150229
Screenshot 2023-09-27 150317
Screenshot 2023-09-28 140256
Screenshot 2023-10-01 151259

### PR DESCRIPTION
**Pull request by YuriyHryshchenko**
### Type of Pull Request *
- [ ] CHANGE (fix or feature that would cause existing functionality to not work as expected)
- [ ] FEATURE (non-breaking change which adds functionality)
- [x] BUGFIX (non-breaking change which fixes an issue)
- [ ] ENHANCEMENT  (non-breaking change which improves existing functionality)
- [ ] NONE (if none of the other choices apply. For example, tooling, build system, CI, docs, etc.)

### Related links
 
**Issue link**
[bugFix694](https://github.com/ita-social-projects/dokazovi-requirements/issues/694)
 
 
### Description *
Selected current user and provided it to component to show info on personal info page. Create new props type ```isCurrentUser``` to not show button "Скасувати зміни" on personal info page.

### CODE REVIEW

File: src/old/lib/components/Users/LoginModal.tsx [hunk 1]
```diff
@@ -42,6 +43,7 @@ export const LoginModal: React.FC = () => {
   });
 
   const [boundAuthorities] = useActions([getAuthoritiesAsyncAction]);
+  const [boundCities] = useActions([fetchCities]);
```
Comment (skyboyer) [inline src/old/lib/components/Users/LoginModal.tsx:46]: are those changes needed for fixing 694? or included by a mistake?

Comment (YuriyHryshchenko) [reply src/old/lib/components/Users/LoginModal.tsx:46]: Yes, needed, because in App component we fetch cities but while user is unauthorized it is rejected to fetch cities, so we got empty array. When i logged in and go to Personal Info it hadn`t cities - just empty array - so we cant set city in field. To fix this i made fetching cities after successful login.

**Review by skyboyer — APPROVED** [review]
